output:
  formats:
    - format: line-number

linters-settings:
  lll:
    line-length: 120
  staticcheck:
    checks:
      - all

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - staticcheck
    - unconvert
    - unused