---
services:
  kqueuey:
    build:
      dockerfile: Dockerfile
      context: .
    command: |
      -logLevel=debug
      -logFormat=json
    environment:
      CONFIG_PATH: "."
    volumes:
      - ./kqueuey-config.yaml:/kqueuey-config.yaml
