storage:
  num_compactors: 4
  compression_type: snappy
  sync_writes: false

raft:
  nodes:
    - id: 1
      bind_addr: 127.0.0.1:1111
      storage_dir: path1
    - id: 2
      bind_addr: 127.0.0.1:1211
      storage_dir: path2
    - id: 3
      bind_addr: 127.0.0.1:1311
      storage_dir: path3
